apiVersion: 1
datasources:
  - name: Lab Prometheus
    type: prometheus
    uid: prom-lab
    access: proxy
    url: http://metrics:9090
    isDefault: true
    editable: false
    jsonData:
      httpMethod: POST
